
# how to configure the augmentations
# it's also possible to copy paste here for a finer control

defaults:
  - _self_
  - augmentations: symmetric.yaml
  - wandb: private.yaml
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# disable hydra outputs
hydra:
  output_subdir: null
  run:
    dir: .

name: "bb-detach-dom"
method: "byol"
backbone:
  name: "resnet18" #"resnet18"
  norm: "bin" #in, bn, bin
method_kwargs:
  proj_hidden_dim: 2048
  proj_output_dim: 256
  pred_hidden_dim: 4096
momentum:
  base_tau: 0.99
  final_tau: 1.0
data:
  dataset: "domain"
  num_classes: 65
  num_domains: 4
  domain_mapper: {0: 'art', 1: 'clipart', 2: 'product', 3: 'realworld'}
  train_path: "/content/drive/MyDrive/BTP/Baseline/train_new/"
  val_path: "/content/drive/MyDrive/BTP/Baseline/test_new/"  # remove this if there's no validation dir
  format: "image_folder" # data format, supports "image_folder", "dali" or "h5"
  num_workers: 2
  no_labels: False
  # set this to True if the dataset is not stored as subfolders for each class
  # if no labels are provided, "h5" is not supported
  # convert a custom dataset by following `scripts/utils/convert_imgfolder_to_h5.py`
optimizer:
  name: "lars"
  batch_size: 64
  lr: 0.75
  classifier_lr: 0.1
  weight_decay: 1e-5
  kwargs:
    clip_lr: True
    eta: 0.02
    exclude_bias_n_norm: True
scheduler:
  name: "warmup_cosine"
checkpoint:
  enabled: False
  dir: "/content/drive/MyDrive/BTP/Baseline/checkpoints_domain/"
  frequency: 10
auto_resume:
  enabled: True
auto_umap:
  enabled: True
  dir: "/content/auto_umap/"
  frequency: 10

# overwrite PL stuff
max_epochs: 150
devices: [0] #[0, 1]
accelerator: "gpu"
# strategy: "ddp"
# precision: 16
# sync_batchnorm: True
